### ISSUE TITLE
Hints

### ISSUE THREAD

**Issue by mlevkov** [jzcoder/pycharm-logging-course#1]
Hints are sometimes very clear, and sometime are very vague. Take a look at lesson 2 task 7. Also, instructions are limited. Please be more explicit.

**Comment by jzcoder** [comment]
Thank you for your comment. I will try to re-visit the instructions and improve on them.

Some of the hints are very explicit, others I wanted to make people try and think a little harder on the solution. In these cases, I usually have detailed instructions on what you should do in the task description.

I made a feature request to JetBrains to allow for multiple hints. That way, the first hint could be just a little help in the right direction, and the second hint could be the correct answer.
