### ISSUE TITLE
How should I use this in standard PyCharm ?

### ISSUE THREAD

**Issue by cbueche** [jzcoder/pycharm-logging-course#2]
Hi,

thanks for your training material, but I would like to use it in my standard, commercial Pycharm. Is there a way to do this ?

Thx,
Charles

**Comment by jzcoder** [comment]
You can not use this in standard PyCharm. You need the special Educational Edition. It's free, and can be installed side-by-side with a full PyCharm installation. I read in one of the forums they plan on releasing a plug-in for PyCharm in the future, but for now you can download the Educational Edition at:

https://www.jetbrains.com/pycharm-educational/download/
